# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Glasfaser im Hanseviertel
email: info@glasfaser-im-hanseviertel.de
description: > # this means to ignore newlines until "baseurl:"
  Die Webseite informiert über den aktuellen Stand der Bemühungen,
  ein Glasfaser-Netz im Hanseviertel Lüneburg aufbauen zu lassen.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.glasfaser-im-hanseviertel.de" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
